name: Deploy develop votee lending user
run-name: ${{ github.actor }} is deploying develop branch🚀
on:
  push:
    branches:
      - 'main'
jobs:
  Deploy:
    runs-on: [self-hosted, votee-lending-user]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16.17
        uses: actions/setup-node@v2
        with:
          node-version: 16.17
      - run: |
          yarn
          pm2 reload pm2.json
